const HOST=window.location.host;
const API_BASE=(location.port==='8080'||location.port==='')?`http://${location.hostname}:8000`:'';
const SIGNALING_URL=`${location.protocol==='https:'?'wss':'ws'}://${HOST}/ws/signaling`;
const AUDIO_URL=`${location.protocol==='https:'?'wss':'ws'}://${HOST}/ws/audio`;
const STORAGE_KEY='ai_voice_agreements_v3', CALLS_KEY='ai_voice_calls_v3', SETTINGS_KEY='ai_voice_settings_v3';
const ICE_CONFIG={iceServers:[{urls:'stun:stun.l.google.com:19302'}]};
let signalingWs=null,audioWs=null,pc=null,localStream=null,audioContext=null,processor=null,myId=null,mode=null;
let timerId=null,timerSeconds=0,activeCallId=null,demoTimers=[],lastProtocol=null,lastTranscript='',currentCallStarted=null,currentDetected=null,settings=loadSettings();
const $=id=>document.getElementById(id);
const els={status:$('status'),dot:$('statusDot'),log:$('log'),caller:$('callerBtn'),listener:$('listenerBtn'),demo:$('demoBtn'),stop:$('stopBtn'),timer:$('timer'),callState:$('callState'),callHint:$('callHint'),badge:$('callBadge'),stt:$('sttState'),ai:$('aiState'),found:$('foundState'),transcript:$('transcript'),protocol:$('protocol'),count:$('agreementCount'),list:$('agreementList'),empty:$('emptyAgreements'),modal:$('modal')};
const labels={high:'Высокий',medium:'Средний',low:'Низкий',pending:'В работе',done:'Выполнено',cancelled:'Отменено'};
function log(m){const line=`[${new Date().toLocaleTimeString()}] ${m}`;els.log.textContent+=`\n${line}`;els.log.scrollTop=els.log.scrollHeight;console.log(m)}
function status(text,active=false){els.status.textContent=text;els.dot.style.background=active?'#55c78b':'#999'}
function uid(prefix='id'){return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function read(key, fallback){try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}}
function write(key,val){localStorage.setItem(key,JSON.stringify(val))}
function getData(){return read(STORAGE_KEY,[])}
function getCalls(){return read(CALLS_KEY,[])}
function loadSettings(){return {...{autoCreateTasks:true,autoCreateCalendar:true,askConfirmation:true,autoPriority:true,triggerPhrases:['отправлю','подготовлю','согласуем','встречаемся','пришлю']},...read(SETTINGS_KEY,{})}}
function saveSettingsLocal(v){settings=v;write(SETTINGS_KEY,v)}
function normalizeAgreement(a={},i=0){return{id:a.id||uid('agr'),contractName:a.contractName||a.contract_name||`Договор №${15+i}`,client:a.client||a.clientName||'Клиент',text:a.text||a.agreement||a.agreement_text||'',owner:a.owner||'Менеджер',deadline:a.deadline||'',priority:a.priority||'medium',status:a.status||'pending',details:a.details||'',callId:a.callId||a.call_id||activeCallId||'',contractId:a.contractId||a.contract_id||'',createdAt:a.createdAt||new Date().toISOString(),updatedAt:a.updatedAt||new Date().toISOString()}}
function saveData(data, sync=true){write(STORAGE_KEY,data);renderAgreements();if(sync)data.forEach(x=>apiSync(x))}
async function api(path,opts={}){if(!API_BASE)throw new Error('API недоступен');const r=await fetch(API_BASE+path,{headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);return r.status===204?null:r.json()}
async function apiSync(item){try{await api('/protocol/agreement',{method:'POST',body:JSON.stringify(item)})}catch(e){log('API sync: '+e.message)}}
function protocolToAgreements(data){const result=[],contracts=Array.isArray(data.contracts)?data.contracts:[];contracts.forEach((c,ci)=>{(c.agreements||[]).forEach((a,i)=>{const task=(c.tasks||[])[i]||{};result.push(normalizeAgreement({contractName:c.contract_name||c.contractName||`Договор №${15+ci}`,contractId:c.contract_id,text:typeof a==='string'?a:a.text,details:c.details,owner:task.owner,deadline:task.deadline,priority:task.priority||'medium'},result.length))})});if(!contracts.length)(data.agreements||[]).forEach((a,i)=>{const task=(data.tasks||[])[i]||{};result.push(normalizeAgreement({contractName:task.contract_name||task.contractName||`Договор №${15+i}`,text:typeof a==='string'?a:a.text,owner:task.owner,deadline:task.deadline,priority:task.priority},i))});return result}
function switchPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active-page'));$(id).classList.add('active-page');document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.page===id));if(id==='agreementsPage')renderAgreements()}
function isOverdue(a){return a.status==='pending'&&a.deadline&&new Date(a.deadline+'T23:59:59')<new Date()}
function renderAgreements(){const all=getData();els.count.textContent=all.length;const q=($('searchInput')?.value||'').toLowerCase(),sf=$('statusFilter')?.value||'all',pf=$('priorityFilter')?.value||'all';const filtered=all.filter(a=>(sf==='all'||a.status===sf)&&(pf==='all'||a.priority===pf)&&(!q||[a.contractName,a.client,a.text,a.owner,a.details].join(' ').toLowerCase().includes(q)));$('totalStat').textContent=all.length;$('pendingStat').textContent=all.filter(a=>a.status==='pending').length;$('doneStat').textContent=all.filter(a=>a.status==='done').length;$('overdueStat').textContent=all.filter(isOverdue).length;const overdue=all.filter(isOverdue);const ns=$('notificationStrip');if(overdue.length){ns.hidden=false;ns.innerHTML=`⚠ <b>${overdue.length}</b> ${overdue.length===1?'договорённость требует':'договорённостей требуют'} внимания: есть просроченные сроки.`}else ns.hidden=true;els.list.innerHTML=filtered.map(a=>`<article class="agreement-card ${isOverdue(a)?'overdue':''}"><div class="agreement-main"><h3>${esc(a.contractName)}</h3><div class="client">${esc(a.client||'Клиент не указан')} · ${esc(a.owner)}</div><div class="agreement-text">${esc(a.text)}</div><div class="meta"><span class="pill ${a.priority}">${labels[a.priority]}</span><span class="pill ${a.status}">${labels[a.status]}</span>${a.deadline?`<span class="pill ${isOverdue(a)?'high':''}">Срок: ${esc(formatDate(a.deadline))}</span>`:''}${a.callId?`<span class="pill">Звонок: ${esc(a.callId.slice(-8))}</span>`:''}</div>${a.details?`<p class="client details">${esc(a.details)}</p>`:''}</div><div class="agreement-actions"><button class="icon-btn" onclick="editAgreement('${a.id}')">Изменить</button>${a.status==='pending'?`<button class="icon-btn" onclick="completeAgreement('${a.id}')">✓ Выполнить</button>`:''}<button class="icon-btn delete" onclick="deleteAgreement('${a.id}')">Удалить</button></div></article>`).join('');els.empty.hidden=filtered.length!==0;if(!filtered.length&&all.length)els.empty.hidden=true}
function formatDate(d){const x=new Date(d);return isNaN(x)?d:x.toLocaleDateString('ru-RU')}
function openModal(item=null){$('agreementForm').reset();$('editId').value=item?.id||'';$('modalTitle').textContent=item?'Изменить договорённость':'Новая договорённость';$('contractName').value=item?.contractName||'';$('clientName').value=item?.client||'';$('agreementText').value=item?.text||'';$('owner').value=item?.owner||'Менеджер';$('deadline').value=item?.deadline||'';$('priority').value=item?.priority||'medium';$('agreementStatus').value=item?.status||'pending';$('details').value=item?.details||'';els.modal.hidden=false}
function closeModal(){$('modal').hidden=true}
window.editAgreement=id=>{const a=getData().find(x=>x.id===id);if(a)openModal(a)};
window.completeAgreement=async id=>{const all=getData(),a=all.find(x=>x.id===id);if(!a)return;a.status='done';a.updatedAt=new Date().toISOString();saveData(all);log(`Договорённость выполнена: ${a.text}`);await createCRMTask(a,'done')};
window.deleteAgreement=async id=>{const a=getData().find(x=>x.id===id);if(!a||!confirm(`Удалить договорённость «${a.text}»?`))return;write(STORAGE_KEY,getData().filter(x=>x.id!==id));renderAgreements();try{await api(`/protocol/agreement/${encodeURIComponent(id)}`,{method:'DELETE'})}catch{}log('Договорённость удалена')};
$('agreementForm').addEventListener('submit',async e=>{e.preventDefault();const data=getData(),id=$('editId').value,item=normalizeAgreement({id:id||uid('agr'),contractName:$('contractName').value,client:$('clientName').value,text:$('agreementText').value,owner:$('owner').value,deadline:$('deadline').value,priority:$('priority').value,status:$('agreementStatus').value,details:$('details').value,callId:activeCallId});const next=id?data.map(x=>x.id===id?item:x):[item,...data];write(STORAGE_KEY,next);renderAgreements();closeModal();await apiSync(item);if(!id&&settings.autoCreateTasks)await createCRMTask(item);if(!id&&settings.autoCreateCalendar&&/встреч|созвон|звонок/i.test(item.text))await createCalendarEvent(item);log(id?'Договорённость изменена':'Новая договорённость сохранена')});
function renderProtocol(data){lastProtocol=data;const contracts=data.contracts?.length?data.contracts:[{contract_name:'Общий разговор',agreements:data.agreements||[],tasks:data.tasks||[]}];els.protocol.classList.remove('empty-state');els.protocol.innerHTML=contracts.map((c,i)=>`<div class="contract-preview"><h3>${esc(c.contract_name||`Договор №${i+1}`)}</h3>${(c.agreements||[]).map(a=>`<p>• ${esc(typeof a==='string'?a:a.text||'')}</p>`).join('')}${(c.tasks||[]).map(t=>`<span class="task-chip">${esc(t.owner||'—')}: ${esc(t.task||'—')}${t.deadline?' · '+esc(t.deadline):''}</span>`).join('')}</div>`).join('');els.found.textContent=`${protocolToAgreements(data).length} договорённостей`;const summary=data.summary||buildSummary(data);$('summary').textContent=summary}
function buildSummary(data){const n=protocolToAgreements(data).length,c=data.contracts?.length||0;return `Обсуждены ${c||'несколько'} ${c===1?'договор':'договоров'}. Зафиксировано ${n} договорённост${n===1?'ь':'и'}. По результатам разговора сформированы задачи и сроки.`}
function appendTranscript(text,who='Собеседник'){if(els.transcript.classList.contains('transcript-empty'))els.transcript.innerHTML='';const div=document.createElement('div');div.className='transcript-line';div.innerHTML=`<strong>${esc(who)}:</strong>${esc(text)}`;els.transcript.appendChild(div);els.transcript.scrollTop=els.transcript.scrollHeight;lastTranscript+=(lastTranscript?' ':'')+text}
function startTimer(){clearInterval(timerId);timerSeconds=0;els.timer.textContent='00:00';timerId=setInterval(()=>{timerSeconds++;els.timer.textContent=`${String(Math.floor(timerSeconds/60)).padStart(2,'0')}:${String(timerSeconds%60).padStart(2,'0')}`},1000)}
function stopTimer(){clearInterval(timerId);timerId=null}
function setCallActive(active,label='Идёт звонок'){els.stop.disabled=!active;els.caller.disabled=active;els.listener.disabled=active;els.demo.disabled=active;els.badge.textContent=active?'Активен':'Не активен';els.badge.classList.toggle('active',active);els.callState.textContent=label;status(active?'Звонок активен':'Готов к работе',active)}
async function startCall(selected){if(!$('consentBtn').dataset.accepted){alert('Сначала подтвердите уведомление о записи разговора.');return}mode=selected;activeCallId=uid('call');currentCallStarted=new Date();lastTranscript='';setCallActive(true);startTimer();els.stt.textContent='Запуск';els.ai.textContent='Ожидание';try{await api(`/protocol/start?call_id=${encodeURIComponent(activeCallId)}`,{method:'POST'});localStream=await navigator.mediaDevices.getUserMedia({audio:selected==='caller',video:false});connectSignaling()}catch(e){log('Медиа/API недоступно: '+e.message);runDemo(false)}}
function connectSignaling(){signalingWs=new WebSocket(SIGNALING_URL);signalingWs.onopen=()=>{log('Signaling подключён');status('Ожидание соединения',true)};signalingWs.onmessage=async e=>{const m=JSON.parse(e.data);if(m.type==='init'){myId=m.id;connectAudio();await createPeerConnection()}else if(m.type==='offer'){await pc.setRemoteDescription(m.sdp);const a=await pc.createAnswer();await pc.setLocalDescription(a);signalingWs.send(JSON.stringify({type:'answer',sdp:pc.localDescription}))}else if(m.type==='answer')await pc.setRemoteDescription(m.sdp);else if(m.type==='candidate'){try{await pc.addIceCandidate(m.candidate)}catch{}}};signalingWs.onerror=()=>log('Ошибка сигнализации')}
async function createPeerConnection(){pc=new RTCPeerConnection(ICE_CONFIG);localStream?.getTracks().forEach(t=>pc.addTrack(t,localStream));pc.onicecandidate=e=>{if(e.candidate&&signalingWs?.readyState===1)signalingWs.send(JSON.stringify({type:'candidate',candidate:e.candidate}))};pc.onconnectionstatechange=()=>log('WebRTC: '+pc.connectionState);const offer=await pc.createOffer();await pc.setLocalDescription(offer);signalingWs.send(JSON.stringify({type:'offer',sdp:pc.localDescription}));if(mode==='caller')startAudioCapture()}
function connectAudio(){audioWs=new WebSocket(`${AUDIO_URL}?call_id=${myId}`);audioWs.binaryType='arraybuffer';audioWs.onopen=()=>{els.stt.textContent='Работает';log('Аудио-канал подключён')};audioWs.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.type==='transcript'){appendTranscript(m.text);els.ai.textContent='Анализирует';detectLiveAgreement(m.text)}else if(m.type==='protocol'){const data=parseJSON(m.content);if(data){renderProtocol(data);const incoming=protocolToAgreements(data);saveData([...mergeUnique(incoming,getData())]);els.ai.textContent='Готов';}}}catch(err){log('Ошибка ответа: '+err.message)}}}
function startAudioCapture(){audioContext=new AudioContext({sampleRate:16000});const source=audioContext.createMediaStreamSource(localStream);processor=audioContext.createScriptProcessor(4096,1,1);processor.onaudioprocess=e=>{if(audioWs?.readyState===1)audioWs.send(float32ToInt16(e.inputBuffer.getChannelData(0)))};source.connect(processor);processor.connect(audioContext.destination);audioContext.resume()}
function float32ToInt16(a){const b=new Int16Array(a.length);for(let i=0;i<a.length;i++){const s=Math.max(-1,Math.min(1,a[i]));b[i]=s<0?s*32768:s*32767}return b.buffer}
function parseJSON(s){try{return JSON.parse(String(s).replace(/```json|```/g,'').trim())}catch{return null}}
function mergeUnique(items,existing){const keys=new Set(existing.map(x=>`${x.contractName}|${x.text}`));return [...items.filter(x=>{const k=`${x.contractName}|${x.text}`;if(keys.has(k))return false;keys.add(k);return true}),...existing]}
function detectLiveAgreement(text){if(!settings.askConfirmation)return;const phrases=settings.triggerPhrases||[];if(!phrases.some(p=>text.toLowerCase().includes(p.toLowerCase())))return;currentDetected={text,contractName:'Обнаружено во время звонка',owner:'Менеджер',priority:'medium'};$('liveAgreementText').textContent=text;$('liveAgreementBox').hidden=false}
function confirmDetected(){if(!currentDetected)return;openModal(normalizeAgreement(currentDetected));$('editId').value='';currentDetected=null;$('liveAgreementBox').hidden=true}
async function createCRMTask(a,status=null){if(!settings.autoCreateTasks)return;try{const r=await api('/integrations/crm/task',{method:'POST',body:JSON.stringify({call_id:a.callId||activeCallId||'manual',agreement_id:a.id,owner:a.owner,task:a.text,deadline:a.deadline||null,contract_id:a.contractId||null,contract_name:a.contractName,priority:a.priority})});if(status)await api(`/integrations/crm/task/${r.task.id}`,{method:'PATCH',body:JSON.stringify({status})});log('CRM: задача создана')}catch(e){log('CRM: '+e.message)}}
async function createCalendarEvent(a){try{await api('/integrations/calendar/event',{method:'POST',body:JSON.stringify({call_id:a.callId||activeCallId||'manual',agreement_id:a.id,title:a.text,time:a.deadline||'По договорённости',participants:[a.owner]})});log('Календарь: событие создано')}catch(e){log('Календарь: '+e.message)}}
function demoProtocol(){return{topic:'Обсуждение трёх договоров',participants:[{role:'Менеджер'},{role:'Клиент'}],summary:'Клиент подтвердил дальнейшие действия по трём договорам: отправка КП, подтверждение количества оборудования и встреча.',contracts:[{contract_id:'15',contract_name:'Договор №15',agreements:['Отправить коммерческое предложение до пятницы'],tasks:[{owner:'Менеджер',task:'Отправить КП',deadline:'2026-10-09',priority:'high'}]},{contract_id:'18',contract_name:'Договор №18',agreements:['Подтвердить количество мониторов до 20 ноября'],tasks:[{owner:'Клиент',task:'Подтвердить количество мониторов',deadline:'2026-11-20',priority:'medium'}]},{contract_id:'21',contract_name:'Договор №21',agreements:['Провести встречу во вторник в 14:00'],tasks:[{owner:'Менеджер',task:'Провести встречу',deadline:'2026-10-13',priority:'high'}]}]}}
async function runDemo(asCall=true){demoTimers.forEach(clearTimeout);demoTimers=[];activeCallId=uid('call');currentCallStarted=new Date();lastTranscript='';setCallActive(true,asCall?'Демо-звонок':'Демо-режим');startTimer();els.stt.textContent='Работает';els.ai.textContent='Анализирует';els.transcript.className='';els.transcript.innerHTML='';els.protocol.innerHTML='';$('summary').textContent='Анализ разговора выполняется…';const lines=[['Менеджер','По договору №15 я отправлю коммерческое предложение до пятницы.'],['Клиент','По договору №18 мы подтвердим количество мониторов до 20 ноября.'],['Менеджер','И ещё по договору №21 давайте встретимся во вторник в 14:00.'],['Клиент','Договорились, встречу подтверждаю.']];lines.forEach((x,i)=>demoTimers.push(setTimeout(()=>{appendTranscript(x[1],x[0]);detectLiveAgreement(x[1])},i*850)));demoTimers.push(setTimeout(async()=>{const data=demoProtocol();renderProtocol(data);const incoming=protocolToAgreements(data).map(x=>({...x,callId:activeCallId,client:'Тестовый клиент'}));write(STORAGE_KEY,mergeUnique(incoming,getData()));renderAgreements();await apiSaveProtocol(data);for(const a of incoming){await apiSync(a);if(settings.autoCreateTasks)await createCRMTask(a);if(settings.autoCreateCalendar&&/встреч/i.test(a.text))await createCalendarEvent(a)}els.ai.textContent='Готов';els.stt.textContent='Готово';await finishCallRecord(data);log('Демо завершено: 3 договора разделены, сохранены и отправлены в CRM/календарь');stopCall(false)},4000))}
async function apiSaveProtocol(data){try{await api('/protocol/structured',{method:'POST',body:JSON.stringify({...data,call_id:activeCallId})})}catch(e){log('Протокол API: '+e.message)}}
async function finishCallRecord(protocol){const call={id:activeCallId,client:'Тестовый клиент',startedAt:currentCallStarted?.toISOString()||new Date().toISOString(),finishedAt:new Date().toISOString(),duration:timerSeconds,status:'completed',summary:protocol.summary||buildSummary(protocol),transcription:lastTranscript,agreementIds:protocolToAgreements(protocol).map(x=>x.id),protocol};const calls=getCalls();write(CALLS_KEY,[call,...calls.filter(x=>x.id!==call.id)].slice(0,100));try{await api('/protocol/calls',{method:'POST',body:JSON.stringify(call)});await api(`/protocol/${encodeURIComponent(activeCallId)}/finalize`,{method:'POST'})}catch(e){log('История API: '+e.message)}}
function stopCall(save=true){demoTimers.forEach(clearTimeout);demoTimers=[];processor?.disconnect();audioContext?.close();pc?.close();signalingWs?.close();audioWs?.close();localStream?.getTracks().forEach(t=>t.stop());processor=audioContext=null;pc=signalingWs=audioWs=localStream=null;stopTimer();setCallActive(false,'Готов к звонку');els.timer.textContent='00:00';els.callHint.textContent='Результат сохраняется во вкладке «Договорённости».';if(save&&activeCallId&&lastTranscript){finishCallRecord(lastProtocol||{summary:buildSummary({contracts:[],agreements:[]})})}log('Звонок завершён')}
function showPanel(title,eyebrow,html){$('panelTitle').textContent=title;$('panelEyebrow').textContent=eyebrow;$('panelContent').innerHTML=html;$('panelModal').hidden=false}
function closePanel(){$('panelModal').hidden=true}
async function showHistory(){let calls=getCalls();try{const r=await api('/protocol/calls/history');calls=r.calls||calls;write(CALLS_KEY,calls)}catch{}const html=calls.length?calls.map(c=>`<div class="history-item"><div><b>${esc(c.client||'Клиент')}</b><p>${esc(new Date(c.startedAt).toLocaleString('ru-RU'))} · ${Math.floor((c.duration||0)/60)}:${String((c.duration||0)%60).padStart(2,'0')}</p><span class="pill">${(c.agreementIds||[]).length} договорённостей</span></div><div class="history-actions"><button class="btn btn-outline btn-small" onclick="viewCall('${c.id}')">Открыть</button><button class="icon-btn delete" onclick="deleteCall('${c.id}')">Удалить</button></div></div>`).join(''):'<div class="empty-state">История пока пуста. Проведите демо-звонок.</div>';showPanel('История звонков','ИСТОРИЯ',html)}
window.viewCall=id=>{const c=getCalls().find(x=>x.id===id);if(!c)return;showPanel('Звонок '+id.slice(-8),'ПРОСМОТР',`<div class="call-detail"><b>${esc(c.client)}</b><p>${esc(new Date(c.startedAt).toLocaleString('ru-RU'))}</p><h3>Резюме</h3><p>${esc(c.summary)}</p><h3>Транскрипция</h3><div class="transcript-history">${esc(c.transcription||'Нет транскрипции')}</div><h3>Договорённости</h3><p>${(c.agreementIds||[]).length} записей сохранено.</p></div>`)};
window.deleteCall=async id=>{write(CALLS_KEY,getCalls().filter(x=>x.id!==id));try{await api(`/protocol/calls/${encodeURIComponent(id)}`,{method:'DELETE'})}catch{}showHistory()};
async function showAnalytics(){const a=getData(),calls=getCalls(),done=a.filter(x=>x.status==='done').length,over=a.filter(isOverdue).length;let tasks=[],events=[];try{tasks=(await api('/integrations/crm/tasks')).tasks||[];events=(await api('/integrations/calendar/events')).events||[]}catch{}const byPriority=['high','medium','low'].map(p=>`<div class="bar-row"><span>${labels[p]}</span><div class="bar"><i style="width:${a.length?Math.round(a.filter(x=>x.priority===p).length/a.length*100):0}%"></i></div><b>${a.filter(x=>x.priority===p).length}</b></div>`).join('');showPanel('Аналитика и KPI','АНАЛИТИКА',`<div class="analytics-grid"><div><span>Звонков</span><b>${calls.length}</b></div><div><span>Договорённостей</span><b>${a.length}</b></div><div><span>Выполнено</span><b>${done}</b></div><div><span>Просрочено</span><b>${over}</b></div><div><span>CRM задач</span><b>${tasks.length}</b></div><div><span>Событий календаря</span><b>${events.length}</b></div></div><h3>Приоритеты</h3>${byPriority}<h3>Доля выполнения</h3><div class="big-kpi">${a.length?Math.round(done/a.length*100):0}%</div><p class="muted">Метрики рассчитываются по данным текущего прототипа.</p>`)}
async function showSettings(){let s=settings;try{s=await api('/protocol/settings');saveSettingsLocal(s)}catch{}showPanel('Настройки автоматизации','НАСТРОЙКИ',`<form id="settingsForm" class="settings-form"><label><input type="checkbox" id="sTasks" ${s.autoCreateTasks?'checked':''}> Автоматически создавать задачи CRM</label><label><input type="checkbox" id="sCalendar" ${s.autoCreateCalendar?'checked':''}> Создавать события календаря</label><label><input type="checkbox" id="sConfirm" ${s.askConfirmation?'checked':''}> Показывать подтверждение обнаруженной договорённости</label><label><input type="checkbox" id="sPriority" ${s.autoPriority?'checked':''}> Автоматически определять приоритет</label><label>Триггерные фразы<textarea id="sPhrases" rows="4">${esc((s.triggerPhrases||[]).join(', '))}</textarea></label><button class="btn btn-primary" type="submit">Сохранить настройки</button></form>`);$('settingsForm').onsubmit=async e=>{e.preventDefault();const next={autoCreateTasks:$('sTasks').checked,autoCreateCalendar:$('sCalendar').checked,askConfirmation:$('sConfirm').checked,autoPriority:$('sPriority').checked,triggerPhrases:$('sPhrases').value.split(',').map(x=>x.trim()).filter(Boolean)};saveSettingsLocal(next);try{await api('/protocol/settings',{method:'PUT',body:JSON.stringify(next)})}catch{}closePanel();log('Настройки сохранены')}}
async function showAudit(){try{const r=await api('/protocol/audit');showPanel('Журнал действий','БЕЗОПАСНОСТЬ',(r.events||[]).map(e=>`<div class="audit-item"><b>${esc(e.action)}</b><span>${esc(new Date(e.timestamp).toLocaleString('ru-RU'))}</span><p>${esc(e.details||e.entity+' '+e.entity_id)}</p></div>`).join('')||'<div class="empty-state">Аудит пока пуст.</div>')}catch{showPanel('Журнал действий','БЕЗОПАСНОСТЬ','API недоступен. Запустите FastAPI, чтобы посмотреть аудит.')}}
$('historyBtn').onclick=showHistory;$('analyticsBtn').onclick=showAnalytics;$('settingsBtn').onclick=showSettings;
$('callerBtn').onclick=()=>startCall('caller');$('listenerBtn').onclick=()=>startCall('listener');$('demoBtn').onclick=()=>runDemo(true);$('stopBtn').onclick=()=>stopCall(true);$('clearTranscriptBtn').onclick=()=>{els.transcript.className='transcript-empty';els.transcript.textContent='Здесь появится текст разговора…';lastTranscript=''};$('clearLogBtn').onclick=()=>els.log.textContent='Журнал очищен.';$('openAgreementsBtn').onclick=()=>switchPage('agreementsPage');$('addAgreementBtn').onclick=()=>openModal();$('emptyAddBtn').onclick=()=>openModal();$('consentBtn').onclick=()=>{$('consentBtn').dataset.accepted='1';$('consentBtn').textContent='✓ Согласие учтено';$('consentBanner').classList.add('accepted')};$('confirmDetectedBtn').onclick=confirmDetected;$('editDetectedBtn').onclick=confirmDetected;$('copySummaryBtn').onclick=async()=>{await navigator.clipboard?.writeText($('summary').textContent);log('Резюме скопировано')};document.querySelectorAll('[data-close-modal]').forEach(x=>x.onclick=closeModal);document.querySelectorAll('[data-close-panel]').forEach(x=>x.onclick=closePanel);$('searchInput').oninput=renderAgreements;$('statusFilter').onchange=renderAgreements;$('priorityFilter').onchange=renderAgreements;document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>switchPage(t.dataset.page));$('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(getData(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ai_voice_agreements.json';a.click();URL.revokeObjectURL(a.href);log('Экспорт выполнен')};window.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();closePanel()}});
renderAgreements();log('Интерфейс готов. Backend-first режим включён.');
